### ISSUE TITLE
Replace `exec` with `run`

### ISSUE THREAD

**Issue by kohane27** [Sonico98/exifaudio.yazi#2]
Hello! Hope you're doing well. Please see the following warning msg:

```
WARNING: `exec` will be deprecated in the next major version v0.3 and replaced by `run`.

Please replace all `exec = ...` with `run = ...`, in your `yazi.toml` and `keymap.toml`.
```

```toml
[plugin]
prepend_previewers = [
    { mime = "audio/*",   run = "exifaudio"}
]
```

Thank you!
